<?php
// Heading
$_['heading_title']     	= 'Tasks';
$_['heading_subtitle']     	= 'administrative tasks generated by customers orders';
$_['body01']     			= '';

// Column
//$_['column_affiliate']  = 'Affiliate Name';
//$_['column_email']      = 'E-Mail';

// Entry
//$_['entry_date_start']  = 'Date Start:';
//$_['entry_date_end']    = 'Date End:';
?>